config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root "static_pages#home"
  get 'static_pages/home'

  get 'static_pages/help'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'

  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  namespace :admin do
    root "users#index"
    resources :users
    resources :categories do 
      resources :words
    end
    resources :words  
  end
  resources :relationships,       only: [:create, :destroy]
  resources :words, only: [:index]

end

app/models/word.rb
class Word < ActiveRecord::Base
	belongs_to :category, inverse_of: :words
	

	has_many :lesson_words, dependent: :destroy
	accepts_nested_attributes_for :lesson_words

	has_many :word_answers, inverse_of: :word
	accepts_nested_attributes_for :word_answers

end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
	before_action :logged_in_user
  	before_action :admin_user

	def index
		if params[:category_id]
			@category = Category.find params[:category_id]
			@words = @category.words.paginate(page: params[:page])
		else
			@words = Word.paginate(page: params[:page])
		end
	end

	def new
		@word = Word.new
		@categories = Category.all
		4.times do 
			answer = @word.word_answers.build
		end
	end
	def show
		@word = Word.find(params[:id])
	end

	def create
		@word = Word.new(word_params)
		if @word.save
			flash[:success] = "Created success"
			redirect_to admin_words_path			
  		end
	end

	def edit
		@admin = current_user
		@word = Word.find(params[:id])
	end
	def update
		@words = Word.find(params[:id])
		if @words.update_attributes(word_params)
		flash[:success] = "Updated Word"
		redirect_to admin_words_path
		end
	end
	def destroy
		@words= Word.find(params[:id]).destroy
		flash[:success] = "Deleted Word"
		redirect_to admin_words_path
	end
	private
	
	def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    def word_params
    	
    	params.require(:word).permit(:content,:category_id, word_answers_attributes: [:id, :content, :correct])
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    lesson_ids = "SELECT id FROM lessons where (user_id = (#{current_user.id}))"
    learned_ids = "SELECT word_id FROM lesson_words where(lesson_id IN (#{lesson_ids}))"
  	if params[:category_id] and params[:category_id] != ''
  		if params[:type] == 'all'
	  		@words = Word.where(category_id: params[:category_id])
	  	elsif params[:type] == 'learned'
  			@words = Word.where("category_id = ? and id IN (#{learned_ids})", params[:category_id])
		  else
  			@words = Word.where("category_id = ? and id NOT IN (#{learned_ids})", params[:category_id])	
		  end
  	else
  		@words = Word.all
  	end
  	
  	@categories = Category.all
  end
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/words/edit.html.erb
<% provide(:title, 'Edit word') %>
<h2>Edit word</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for [:admin, @word] do |f| %>
    	
		<%= f.collection_select :category_id, Category.all, :id,:name%>
      	<%= f.label :content %>
      	<%= f.text_field :content, class: 'form-control' %>

      	<%= f.fields_for :word_answers do |builder| %>
      	<td><%= builder.text_field :content, class: "form-control" %></td>
      	<%= builder.check_box :correct %><br>
      	<% end %>
  		<%= f.submit "Edit", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide(:title, 'All words') %>
<h1>All words</h1>
<%= link_to "Create new word", new_admin_word_path, class: "btn btn-lg btn-primary" %>
<%= will_paginate %>
<ul class="users">
  
  <div class="container">         
	  		<table class="table table-bordered">
		    <thead>
		      <tr>
		        <th>Word</th>
		        <th>Delete</th>
		        <th>Edit</th>
		        <th>Show</th>
		      </tr>
		    </thead>
		    <tbody>
		    <% @words.each do |word| %>
		      <tr>
		        <td><%= word.content %></td>
		        <td><%= link_to "Delete", admin_word_path(word), method: :delete,
                                  data: { confirm: "Are you sure?" }, class: "btn btn-success" %></td>
		        <td><%= link_to "Edit",edit_admin_word_path(word), class: "btn btn-success"%></td>
				<td><%= link_to "Show",admin_word_path(word), class: "btn btn-success"%></td>
		      </tr>
		      <% end %>
		     </tbody>
		  	</table>
		</div>
  
</ul>

<%= will_paginate %>

app/views/admin/words/show.html.erb
<% provide(:title, @word.content) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
		<div class="container">         
	  		<table class="table table-bordered">
		    <thead>
		      <tr>
		        <th>Word</th>
		        <th>Mean</th>
		        <th>Answer1</th>
		        <th>Answer2</th>
		        <th>Answer3</th>
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td><%= @word.content %></td>
		        <td><%= @word.word_answers.where(correct: true).first.content %></td>
		        <td><%= @word.word_answers.where(correct: false).first.content %></td>
				<td><%= @word.word_answers.where(correct: false).second.content %></td>
				<td><%= @word.word_answers.where(correct: false).third.content %></td>
		      </tr>
		     </tbody>
		  	</table>
		</div>
	</section>
  </aside>
</div>