config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root "static_pages#home"
  get 'static_pages/home'

  get 'static_pages/help'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'

  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  namespace :admin do
    root "users#index"
    resources :users
    resources :categories do 
      resources :words
    end
    resources :words  
  end
  resources :relationships,       only: [:create, :destroy]
  resources :words, only: [:index]

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :words, inverse_of: :category
	accepts_nested_attributes_for :words, allow_destroy: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	before_action :logged_in_user
  	before_action :admin_user
	def index
		@categories = Category.paginate(page: params[:page])
	end
	def show
		@category = Category.find(params[:id])
		@word = @category.words
	end
	def edit
		@admin = current_user
		@category = Category.find(params[:id])
	end
	def new
		@category = Category.new
	end
	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Created success"
			redirect_to admin_categories_path
		end
	end
	def update
		@category = Category.find(params[:id])
		if @category.update_attributes(category_params)
		flash[:success] = "Updated Category"
		redirect_to admin_category_path
		end
	end
	def destroy
		@category = Category.find(params[:id]).destroy
		flash[:success] = "Deleted Category"
		redirect_to admin_categories_path
	end
	private
    def category_params
      params.require(:category).permit(:name)
    end
	def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    def list_words
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<li>
  <%= categories.name %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "Delete", admin_categories_path(categories), method: :delete,
                                  data: { confirm: "Are you sure?" } %>
    | <%= link_to "Edit",edit_admin_categories_path(categories)%>
  <% end %>
</li>

app/views/admin/categories/edit.html.erb
<% provide(:title, "Edit category") %>
<h1>Update category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
	<% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide(:title, 'All categories') %>
<h1>All categories</h1>
<%=link_to "Create new category ", new_admin_category_path, class: "btn btn-lg btn-primary"%>

<%= will_paginate %>

<ul class="users">
<div class="container">         
	  		<table class="table table-bordered">
		    <thead>
		      <tr>
		        <th>Category</th>
		        <th>Delete</th>
		        <th>Edit</th>
		        <th>Get all words</th>
		      </tr>
		    </thead>
		    <tbody>
		    <% @categories.each do |category| %>
		      <tr>
		        <td><%= category.name %></td>
		        <td><%= link_to "Delete", admin_category_path(category), method: :delete,
                                  data: { confirm: "Are you sure?" }, class: "btn btn-success" %></td>
		        <td><%= link_to "Edit",edit_admin_category_path(category), class: "btn btn-success"%></td>
				<td><%= link_to "Get words of category", [:admin, category, :words], class: "btn btn-success"%></td>
		      </tr>
		      <% end %>
		     </tbody>
		  	</table>
		</div>
</ul>

<%= will_paginate %>

app/views/admin/categories/new.html.erb
<% provide(:title, "Create new category") %>
<h1>Create new category </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.submit "Create ", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<% provide(:title, @category.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @category.name %>
      </h1>
    </section>
  </aside>
</div>